function myFunction1(smallImg){
fullImg = document.getElementById("imageBox");
document.getElementById("demo").innerHTML=" Muichiro Tokito (時とき透とう 無む一いち郎ろう Tokitō Muichirō?) is a major supporting character of Demon Slayer: Kimetsu no Yaiba. He is a Demon Slayer of the Demon Slayer Corps and the current Mist Hashira (霞かすみ柱ばしら Kasumi Hashira?).[3] Muichiro is a young boy of fair skin and short stature with a lean muscular build along with long, straight hair of a black color that fades to pale turquoise as it approaches his waist. He wears his hair loose with two clumps protruding slightly from each side of his head, a set of marginally shorter hair left down to frame his face, and unruly bangs over his forehead. He also possesses large, empty-looking pale turquoise eyes. He is identical in appearance to his older twin brother Yuichiro.Following his meeting with Tanjiro Kamado and the return of his childhood memories, Muichiro's once empty looking eyes seem to now have a hopeful glimmer that is accompanied with a more upbeat and cheery expression, reminiscent of his former demeanor before the death of Yuichiro.Muichiro wears a dark, slightly turquoise-tinted version of the Demon Slayer uniform. His uniform has longer, looser sleeves that are more reminiscent of those of a kimono than of the standard cuffed uniform. Along with this, the lack of bands of cloth wrapped around his calves gives his uniform an overall loose and sizable appearance. He also has dark blue tabi socks and a pair of white zōri with dark blue straps.Due to Tanjiro's presence around him, Muichiro manifested his Demon Slayer Mark during the battle against the Upper Rank 5 Gyokko. Muichiro's mark is dark red coloured, resembling mist shaped clouds on both his cheeks.";
fullImg.src =smallImg.src;
}
function myFunction2(smallImg){
fullImg = document.getElementById("imageBox");
document.getElementById("demo").innerHTML=" Gyomei Himejima (悲ひ鳴め嶼じま 行ぎょう冥めい Himejima Gyōmei?) is a major supporting character of Demon Slayer: Kimetsu no Yaiba. He is a Demon Slayer of the Demon Slayer Corps and the current Stone Hashira (岩いわ柱ばしら Iwa Bashira?). Gyomei also serves as the mentor of Genya Shinazugawa. Gyomei is a hulking figure among the Demon Slayers. He is one of the tallest characters in the series, easily towering over his fellow Hashira. He is powerfully built and extremely muscular. He has spiky black hair and a prominent scar running horizontally across his forehead. Having been blind since childhood, he has white eyes with no visible irises or pupils. His eyes frequently tear-up when he gets emotional.Gyomei wears a black and white uniform typical of a Demon Slayer, with bandages over his shins resembling kyahan and white zōri with an olive green happi draped over his shoulders. The collared frame of the happi contains the kanji for the Japanese Nianfo/Shin Buddha chant (南な無む阿あ弥み陀だ仏ぶつ Namu Amida Butsu?) from the top-down, along with the separate kanji all over at the back. He also sports a large-beaded necklace around his neck and carries a set of ojuzu beads when he is not engaged in battle.He sustains a scar across his face after being slashed by a crescent moon blade from Kokushibo.[4] His left leg from the knee below was later severed during the battle against Muzan.[5] ";
fullImg.src =smallImg.src;
}

function myFunction3(smallImg){
  fullImg = document.getElementById("imageBox");
  document.getElementById("demo").innerHTML=" Kyojuro Rengoku (煉れん獄ごく 杏きょう寿じゅ郎ろう Rengoku Kyōjurō?) was a major supporting character of Demon Slayer: Kimetsu no Yaiba and a major character in the Mugen Train Arc. He was a Demon Slayer of the Demon Slayer Corps and the late Flame Hashira (炎えん柱ばしら En Bashira?).[2] Kyojuro was a young adult of tall stature and lean-muscular build. He had long bright yellow hair with red streaks akin to flames along with two shoulder-length bangs and two chin-length bangs on the side of his head, black forked eyebrows, and golden eyes that fade to red with white pupils. He was known to be charismatic and had an air of great optimism, having an enthusiastic smile plastered on his face nearly all the time.Kyojuro wore a paler brown version of the regular Demon Slayer uniform, which consisted of a brown gakuran jacket, a white belt around his waist and tattsuke-hakama pants. Over this, he wore a haori with a white-yellow gradient pattern and red flame-like ridges at the end that his father Shinjuro had once worn and more than likely his father had worn when they were the Flame Hashira respectively. Finally, he wore red kyahan with yellow flames erupting from the bottom-up, with pale brown tabi socks and a pair of white zōri with red straps. When he first joined the Demon Slayer Corps, he only wore the regular Demon Slayer uniform but as he rose up the ranks, Kyojuro started wearing a completely white haori before donning on his signature flame-patterned one. ";
  fullImg.src =smallImg.src;
  }
 
function myFunction4(smallImg){
  fullImg = document.getElementById("imageBox");
  document.getElementById("demo").innerHTML=" Sanemi Shinazugawa (不死しなず川がわ 実さね弥み Shinazugawa Sanemi?) is a major supporting character of Demon Slayer: Kimetsu no Yaiba. He is a Demon Slayer of the Demon Slayer Corps and the current Wind Hashira (風かぜ柱ばしら Kaze Bashira?).[2]Sanemi is also the older brother of Genya Shinazugawa, a Demon Slayer who fought alongside Tanjiro Kamado and Nezuko Kamado. Before becoming a Hashira, Sanemi, along with his partner Masachika Kumeno, defeated the former Lower Rank One, Ubume, with Masachika dying as a result. Sanemi is a tall man of very muscular build, with spiky long white hair and large almond-shaped eyes with purple irises. His face and body are covered with scars, accrued over his many years of fighting demons. He cuts his hair short somewhere in between the Rehabilitation Training Arc and the Mugen Train Arc. He is usually seen wearing a crazed expression on his face.He wears a green-tinted version of the standard Demon Slayer uniform, unbuttoned to expose his chest and abs with a white long sleeved shirt over it with the kanji for kill (殺さつ satsu?) etched on the back, white buckles around his shins and tabi socks with a pair of white zōri with green straps.During his battle with Kokushibo, he loses his right index and middle fingers.[3] ";
  fullImg.src =smallImg.src;
}
function myFunction5(smallImg){
   fullImg = document.getElementById("imageBox");
   document.getElementById("demo").innerHTML=" Mitsuri Kanroji (甘かん露ろ寺じ 蜜みつ璃り Kanroji Mitsuri?) is a major supporting character of Demon Slayer: Kimetsu no Yaiba. She is a Demon Slayer of the Demon Slayer Corps and the current Love Hashira (恋こい柱ばしら Koi Bashira?).[5] Mitsuri is a curvaceous young woman of deceptively muscular build and a pale skin complexion. She stands slightly taller than average. She has large round, pale green eyes with long eyelashes and a small beauty mark beneath each of them. She has long, light pink hair that fades into a lime green color at the halfway point, which she wears in three thick braids. She has five shorter, choppy clumps hanging over her face as voluminous bangs, the tips lime green as well. When she was trying to get married, her hair was dyed black in an attempt to make herself look more. Mitsuri wears a heavily modified dark plum colored version of the standard Demon Slayer uniform along with a plain white haori that was gifted to her by Kyojuro Rengoku.[6] Because of its tight fit, the chest area of her jacket and her undershirt is left unbuttoned, and she wears a short pleated mini skirt in place of the usual tattsuke-hakama pants. Additionally, she wears a pair of navy blue thigh-high socks layered with the vertically striped lime-green socks Obanai Iguro gave to her and a pair of white zōri with pink straps tied and fastened with a bow on the front. While at the Swordsmith Village, Mitsuri wore a kimono with floral designs. During her and the other remaining Hashira's fight against Muzan, Mitsuri's left and back braids are cut off by Muzan Kibutsuji's attacks, now shortened to shoulder length, and part of her left ear is also torn at the side.[7] Mitsuri also loses both of her arms in the process of ripping off Muzan's left arm.[8] ";
  fullImg.src =smallImg.src;
 }
function myFunction6(smallImg){
 fullImg = document.getElementById("imageBox");
 document.getElementById("demo").innerHTML="Tengen Uzui (宇う髄ずい 天てん元げん Uzui Tengen?) is a major supporting character of Demon Slayer: Kimetsu no Yaiba and a major character in the Entertainment District Arc. He was a former member of the Demon Slayer Corps, standing as the previous Sound Hashira (音おと柱ばしら Oto Bashira?).[6] Tengen is a very tall, broad-shouldered, and muscular man with lightly-tanned skin and white hair. His hair is of an uneven length, the longest strands reaching his shoulders, and is styled with three more notable, shorter clumps arching up to fall as bangs between his eyes and on either side of his face. He has quite thin, maroon eyes that appear to slant inwards, each with one long eyelash flowing to the far side of his face. He is considered very attractive as noted by many women and even by Zenitsu; this has led him to use his looks as a tool for his missions whenever persuasion is necessary. During his days serving the Demon Slayer Corps, Tengen wears a sleeveless and dark turquoise version of the standard Demon Slayer uniform, along with a wrap of burgundy cloth around his calves with his tattsuke-bakama pants tuck in, and white-strapped Zōri. He also wears two thick, golden rings around his upper arms and what appear to be a pair of finger-less blue gloves, secured around his middle finger with a band of white and his wrists with another set of thinner gold rings, this time with two on each side. As well as this, Tengen sports a white head-wrap that covers his hair, leaving only a thin ponytail visible to fall behind his head from between its layers, which is adorned with a large headband of pale gray that's decorated by six light pink gemstones, three large and arranged in a line, and three small and arranged in a triangle to the far left. A chain of smaller, pale blue gemstones hangs from each side of this headdress, framing his face, and he also wears what looks to be red eye make-up around his left eye, consisting of alternating large and small dots that run inwards, towards his eye. After his retirement from the Demon Slayer Corps due to the injuries he has sustained during his fight with Gyutaro, Tengen changes his appearance to coordinate the loss of his left eye and hand. He now wears a long, aqua colored yukata and a black haori, and replaces his old head-wrap with a dark eyepatch adorned with what look to be the remaining gemstones left over from his old headdress, leaving his hair to fall loosely past his shoulders. ";
 fullImg.src =smallImg.src;
}
function myFunction7(smallImg){
    fullImg = document.getElementById("imageBox");
    document.getElementById("demo").innerHTML=" Shinobu Kocho (胡こ蝶ちょう しのぶ Kochō Shinobu?) is a major supporting character of Demon Slayer: Kimetsu no Yaiba. She is a Demon Slayer of the Demon Slayer Corps and the current Insect Hashira (蟲むし柱ばしら Mushi Bashira?).[2][3] Shinobu is also the younger sister of Kanae Kocho along with her adoptive younger sister Kanao Tsuyuri. After a demon killed her parents, Shinobu joined the Demon Slayer Corps along with her sister in order to protect others from suffering the same fate as her. Shinobu is a petite young woman with a slender build and a pale complexion. She has large eyes that lack pupils, only a haze of gradient purple, making her eyes appear similar to those of insects. She has medium black wavy hair that fades into dark purple at the ends, styled at the back of her head into a flat yakai-maki bun, fastened with a white, turquoise and light purple butterfly ornament. She has center-split, ear-length, voluminous curtain bangs that flow down to frame the sides of her face, with two slightly thinner chin-length locks of hair in front of her ears below them. She stands out among the more physically imposing Hashira due to her diminutive stature and small frame, which is later reinforced by her mentioning that she does not possess enough physical strength to decapitate a demon as the others do. According to Zenitsu, Shinobu is so cute, that she could make a living on her looks alone.Shinobu wears a dark purple standard Demon Slayer uniform with gold buttons, consisting of a dark-purple tinted straight-lined black jacket and matching colored tabi socks and hakama pants, tucked into white butterfly patterned Kyahan fading into pale turquoise then pink around her lower legs, fastened with white ribbons. Over her uniform, she wears a white haori that previously belonged to her older sister, which has a butterfly wing pattern that fades into a pale turquoise then pink color on the sleeves and hem which are cuffed with a black and white dotted trim. She wears white zōri sandals with purple straps for footwear, with a hidden blade in one of the heels. When Shinobu was fourteen, her appearance was altered slightly. Her chin-length strands of hair in front of her ears were tucked in, and she had a different Demon Slayer uniform consisting of silver buttons and cloth a darker shade of purple. She also sported a plain white haori over it.";
    fullImg.src =smallImg.src;
  }
  function myFunction8(smallImg){
    fullImg = document.getElementById("imageBox");
    document.getElementById("demo").innerHTML=" Obanai Iguro (伊い黒ぐろ 小お芭ば内ない Iguro Obanai?) is a major supporting character of Demon Slayer: Kimetsu no Yaiba. He is a Demon Slayer of the Demon Slayer Corps and the current Serpent Hashira (蛇へび柱ばしら Hebi Bashira?).[3] Obanai is a young man of short stature, pale skin complexion, and a fairly muscular build. He has straight-edged black hair of varying lengths, the longest reaching down to his shoulders and the shortest stopping at his cheekbones, which he wears down with two shorter strands hanging between his eyes. His eyes are almond-shaped and tilt upwards on the far sides, and are unique colored due to Obanai possessing heterochromia—his right eye is yellow and his left eye is turquoise. He is partially blind, barely able to see out of his right eye.[4] Obanai's mouth is usually hidden by the bandage he wears over his lower face to hide his large facial scars, which were the result of his family horrifically cutting open his mouth to resemble that of a snake's gape.[5] He wears a navy blue version of the standard Demon Slayer uniform, along with a black and white striped haori, the hem and cuffs of which are striped length ways rather than vertically, which covers his hands. Obanai also sports bandages in place of the leg-wraps around his calves giving the resemblance of kyahan, as well as another set of bandages that cover his mouth, and white with blue-strapped zōri on his feet. He is also always seen with his white snake, Kaburamaru, wrapped around his shoulders.  During the battle with Muzan, Obanai and the other remaining Hashira are attacked by the demon's flailing whips, and Obanai is left with three long slanted scratches over his eyes, rendering him completely blind.[6]When he was a child, Obanai had waist-length hair that he wore tied down his back with a long white bandage and a regular-looking mouth before it got cut by his family. He also wore a plain white kimono.";
    fullImg.src =smallImg.src;
  }
  function myFunction9(smallImg){
    fullImg = document.getElementById("imageBox");
    document.getElementById("demo").innerHTML=" Giyu Tomioka (冨とみ岡おか 義ぎ勇ゆう Tomioka Giyū?) is a major supporting character of Demon Slayer: Kimetsu no Yaiba. He is a Demon Slayer of the Demon Slayer Corps and the current Water Hashira (水みず柱ばしら Mizu Bashira?).[5] Giyu is a fairly tall young man of a lean muscular stature and pale complexion, who is almost always seen wearing a serious and emotionless expression. He has unruly black hair of uneven lengths that sticks up in tufts around his head, which he wears tied back in a low messy ponytail at the base of his neck. His bangs fall over his eyes in an uneven fringe. His eyes are sharp and moderately large, their irises a deep sapphire that fades to a lighter blue and their pupils a bluish-black, and are framed by thin eyebrows.Giyu wears a dark cyan-tinted version of the standard Demon Slayer uniform with buttoned white leg-wrapped kyahan and a pair of white zōri with dark blue straps and tabi socks underneath being the same cyan color as his uniform. Over this, Giyu wears a haori that's split down the middle into two different patterns: the right one a solid dark red, and the left one geometrically patterned with rhombi of green, orange, and yellow. These haori were later noted to have belonged to his late older sister, Tsutako Tomioka, and his deceased friend Sabito.[6]During his battle with Muzan Kibutsuji, he loses his right arm.[7] After the fight, Giyu cuts his hair down to shoulder length, now wearing it loose rather than tied into a ponytail.[8]  While Giyu was training under Sakonji Urokodaki, he wore a red haori which would later make up his current one as well as black tucked-in tattsuke-hakama pants and his current white leg-wrapped kyahan and pair of white zōri with dark blue straps. In addition, he also wears the warding masks that are signature to Sakonji's pupils. For Giyu, it is a white fox mask with light blue eyes.";
    fullImg.src =smallImg.src;
  }
  function myFunctionmc1(smallImg){
    fullImg = document.getElementById("imageBox");
    document.getElementById("mcdescription").innerHTML=" Nezuko Kamado (竈門 禰豆子, Kamado Nezuko) is the second child and oldest daughter of Tanjuro and Kie, who was turned into a demon during the massacre of her family and survived despite Muzan assuming that he failed to sire a sunlight-resistant demon. She serves as motivation and support for Tanjiro, who becomes a Demon Slayer to find a way to turn her back to normal. Though her mind was lost, she retains enough of her memories to keep herself from killing Tanjiro. After two years of hypnotic conditioning by Sakonji, Nezuko regards all humans as her family and will mercilessly attack any demons who threaten them. Instead of consuming human flesh, Nezuko regains energy from sleep, doing so for long periods of time after overexerting herself. Initially, she is unable to speak and wears a bamboo muzzle which Giyu Tomioka gave her to prevent her from biting others. The muzzle is later removed and she regains her speech, albeit broken due to not speaking for more than two years. Nezuko has the usual powers of demons, including regeneration, potent strength, and changing her physical structure, as well as a Blood Demon Art called Exploding Blood (爆血, Bakketsu) that causes her blood to burn at will. Tanjiro generally carries her around in a wooden box, which was a gift from Sakonji, until she develops the ability to survive exposure to sunlight, with Muzan targeting her soon after. Nezuko's mind and humanity are eventually restored during the final battle against Muzan.";
    fullImg.src =smallImg.src;
  }
  function myFunctionmc2(smallImg){
    fullImg = document.getElementById("imageBox");
    document.getElementById("mcdescription").innerHTML=" Tanjiro Kamado (竈門 炭治郎, Kamado Tanjirō) is the oldest son of charcoal sellers Tanjuro and Kie, whose family was killed by Muzan Kibutsuji while he was away selling charcoal; his sister Nezuko survived, but was turned into a demon. Since then, his goal has been to find a cure for her and turn her back into a human; to this end, he decides to become a Demon Slayer. He initially trains under Sakonji Urokodaki to learn the Water Breathing (水の呼吸, Mizu no kokyū) style; he later begins using his family's Hinokami Kagura (ヒノカミ神楽, lit. Dance of the Fire God), based on the original breathing style, Sun Breathing (日の呼吸, Hi no kokyū), eventually utilizing both to create a more sustainable fighting style. He is pure and kind-hearted, always looking after his comrades' well-being and sympathizing with the plight of demons while understanding that their actions cannot be forgiven. His optimism and honesty allow most to enjoy his company, though it also puts him at odds with certain personalities. Tanjiro has a heightened sense of smell, which allows him to detect demons and evade their attacks as well as determine people's true emotions. His skull is exceptionally thick and his headbutts can be used in confrontations. He wields a black sword which occasionally turns crimson red; the change in color is later revealed to be an ability that slows the regeneration of demons. Though he eventually avenges his family during the final battle, he loses his left arm and right eye in the process and is fatally wounded. Both are restored during Muzan's attempt to turn him into his successor by transforming him into a demon, though with the aid of his friends, his humanity is restored.";
    fullImg.src =smallImg.src;
  }
  function myFunctionmc3(smallImg){
    fullImg = document.getElementById("imageBox");
    document.getElementById("mcdescription").innerHTML="Zenitsu Agatsuma (我妻 善逸, Agatsuma Zen'itsu) is a cowardly boy who was forced to join the Demon Slayer Corps around the same time as Tanjiro in order to pay off his debts. He serves as comic relief, with his flighty personality serving as a contrast to Tanjiro's steadfast determination. He trained in the Thunder Breathing (雷の呼吸, Kaminari no kokyū) style with the former Thunder Hashira, but was only able to learn the first form; as a result, he often belittles himself despite being highly skilled. He has accompanied Tanjiro since joining him on a mission, partially out of his love for Nezuko, but also due to recognizing Tanjiro's honesty and kindness. His cowardly personality initially hinders him and he is only able to fight when unconscious or asleep, but he later learns to overcome his fears and take action when necessary. He wields a yellow sword with a lightning bolt design. He has a heightened sense of hearing, which allows him to distinguish a person's true character by the sound of their heartbeat and to track demons.";
    fullImg.src =smallImg.src;
  }
  function myFunctionmc4(smallImg){
    fullImg = document.getElementById("imageBox");
    document.getElementById("mcdescription").innerHTML="Inosuke Hashibira (嘴平 伊之助, Hashibira Inosuke) is a boy who was raised by wild boars and taught to speak by an old man after his mother, Kotoha, sacrificed herself to save him from Doma, the Upper Rank Two. He is illiterate as a result of his upbringing and often forgets or mispronounces names. He uses a self-taught style called Beast Breathing (獣の呼吸, Kedamono no kokyū) and dual wields two indigo-gray serrated swords; when he gets new swords, he purposely chips them to match his preferences and fighting style. He is brash and prone to violence, and while appearing to be dim, has proven himself in battle. He normally hides his face behind a mask made from the head of his deceased boar mother, which he wears to honor her. When he first meets Tanjiro, he is initially hostile towards him, but they become friends as they fight together. He attends Final Selection at the same time as Tanjiro and Zenitsu and, unbeknownst to most, was the first to clear it. He has a heightened sense of touch, which allows him to locate enemies by feeling vibrations in the air.";
    fullImg.src =smallImg.src;
  }
  function myFunctionleader1(smallImg){
    fullImg = document.getElementById("imageBox");
    document.getElementById("leaderdescription").innerHTML="Kagaya Ubuyashiki (産うぶ屋や敷しき 耀かが哉や Ubuyashiki Kagaya?) is a major supporting character of Demon Slayer: Kimetsu no Yaiba. He is the 97th leader of the Demon Slayer Corps[2] known mainly as Oyakata-sama (お館󠄃やかた樣さま? lit. Master) by his subordinates and peers and is also the head of the Ubuyashiki Family.[3][4] Kagaya has light skin and black shoulder length hair. He has a curse mark that is slowly killing him that also makes his skin look as if it was rotting spreading down his face and covering his eyes making him unable to see, by the time of his death this curse had spread all over his body making moving nearly impossible. Muzan at Kagaya's death described him as having the smile of a Buddha. He wears a plain black kimono secured with a tan-colored braided obi over a white juban. His also wears a white, calf-length haori with a unique design of gradient flames of the colors purple and salmon pink rising from the hem up to the half of the sleeves.";
    fullImg.src =smallImg.src;
  }
  function myFunctionleader2(smallImg){
    fullImg = document.getElementById("imageBox");
    document.getElementById("leaderdescription").innerHTML="Muzan Kibutsuji (鬼き舞ぶ辻つじ 無む惨ざん Kibutsuji Muzan?) is the main antagonist of Demon Slayer: Kimetsu no Yaiba. He is the Demon King, the progenitor of all other demons in existence, and the leader of the Twelve Kizuki, an organization made up of the twelve strongest demons under his direct command. [6] A millennium ago during the Heian Era, Muzan was turned into a demon from an experimental treatment for his terminal illness[1] and his goal ever since then has been to live without the fear of death and become truly eternal.[7] He plans to accomplish this in two ways: finding the Blue Spider Lily or creating more demons in hopes that one day, one will eventually be able to conquer his weakness of sunlight.[8][9] It is later revealed that Muzan is also of the same bloodline as the Ubuyashiki Family.[10] Muzan is a tall man with a lean muscular build along with an unnaturally pale skin complexion that can be easily confused as being unhealthy and sickly. He has curly black hair and sharp, almond-shaped eyes. His irises are cat-like in appearance and are of a plum red color. He also possesses sharp, blue nails on his hands. Physically, he appears to be in his twenties. In his first appearance, Muzan was shown wearing a white fedora with a red ribbon and a somewhat extravagant outfit, consisting of an embroidered black tuxedo and a white tie over a black dress shirt and white dress pants. He also wore black loafers. As seen in Rui's memories of meeting Muzan, the Demon King once sported a slightly different hairstyle and outfit in the past. When he met Rui, Muzan's hair was straighter and parted down the middle. He also wore a loose-fitting tuxedo and a white half-cloak over it. During his meeting with the Lower Ranks, he arrived disguised as an elegant woman with a chignon hairstyle while wearing a long black yukata, causing the Lower Ranks to not initially recognize him.[11] Later, he transforms himself into his latest cover identity - the adopted sickly son to an old couple - taking the form of a young child with pale, white skin and black, silky smooth, neatly combed black hair. His main outfit in this disguise is a plain white button-up shirt and black cargo shorts with long tube socks and loafers. ";
    fullImg.src =smallImg.src;
  }
  function myFunctionuppermoon1(smallImg){
    fullImg = document.getElementById("imageBox");
    document.getElementById("uppermoondesciption").innerHTML="Akaza (猗あ窩か座ざ Akaza?) is a major supporting antagonist of Demon Slayer: Kimetsu no Yaiba. He is a demon affiliated with the Twelve Kizuki, holding the position of Upper Rank Three (上じょう弦げんの参さん Jōgen no San?).[3] Over a century ago, Akaza was a human by the name of Hakuji (狛はく治じ Hakuji?)[4], a prodigious martial artist who trained under Keizo[5] while nursing his daughter, Koyuki,[6] who would later become Akaza's fiancée.[7] Akaza was a very muscular young man of average height with skin so fair, it appears bright green-tinged white, decorated by a pattern of thick blue lines, which resemble the criminal tattoos he had as a human. Akaza had short, bright pink hair that fluffed out around his head, and inward-tilting yellow eyes with pink eyelashes and blue sclera that looked somewhat like cracked glass. The kanji for Upper Rank (上じょう弦げん Jōgen?) and the daiji for Three (参さん San?) are etched into his irises as well. During his human days as Hakuji, he had the same hair, just colored black rather than pink, and pale blue eyes with unusually-colored pink eyelashes. He was also very muscular as a human, and, on each of his forearms, he bore three black criminal tattoos. He also wore a dark blue-gray yukata.";
    fullImg.src =smallImg.src;
  }
  function myFunctionuppermoon2(smallImg){
    fullImg = document.getElementById("imageBox");
    document.getElementById("uppermoondesciption").innerHTML="Doma (童どう磨ま Dōma?) is a major supporting antagonist of Demon Slayer: Kimetsu no Yaiba. He is a demon affiliated with the Twelve Kizuki, holding the second highest position, Upper Rank Two (上じょう弦げんの弐に Jōgen no Ni?).[3] Over a century ago, Doma held the position of Upper Rank Six (上じょう弦げんの陸ろく Jōgen no Roku?),[4] and during that tenure, he turned Gyutaro and Ume into demons and introduced them into the Twelve Kizuki.[5][6] He is also the leader of the Eternal Paradise Faith,[7] a cult dedicated to worshipping Doma and a place where he listens to all his followers' troubles and gives them advice.[8] It also acts as a place for Doma to capture and kill humans.[9] This cult also took in Inosuke Hashibira's mother, Kotoha Hashibira,[10] before Doma killed her after finding out that he was eating his followers.[11]";
    fullImg.src =smallImg.src;
  }
  function myFunctionuppermoon3(smallImg){
    fullImg = document.getElementById("imageBox");
    document.getElementById("uppermoondesciption").innerHTML="Kaigaku (獪かい岳がく Kaigaku?) is a supporting antagonist in the Infinity Castle Arc of Demon Slayer: Kimetsu no Yaiba. He is a demon affiliated with the Twelve Kizuki, holding the position of Upper Rank Six (上じょう弦げんの陸ろく Jōgen no Roku?), replacing Daki and Gyutaro after their deaths. Kaigaku was a former Demon Slayer and Zenitsu Agatsuma's senior disciple under the former Thunder Hashira (鳴なり柱ばしら Nari Bashira?), Jigoro Kuwajima. However, sometime during Hashira Training, Kaigaku went on a mission and encountered Upper Rank One, Kokushibo, quickly surrendering to him to save his own skin and later becoming a member of the Twelve Kizuki.[3] As a transformed Demon Slayer and a member of the Upper Ranks, Kaigaku was an extremely powerful demon. This is supported by the fact that he had to receive a lot of Muzan Kibutsuji's blood for him to turn into a demon as users of Total Concentration Breathing are more resistant to the effects of the Demon King's blood.[8] Zenitsu also noted that Kaigaku had eaten a lot of humans in the short period of time between Hashira Training and his encounter with him, further testifying his strength.[9] According to Yushiro, during Kaigaku's short tenure as Upper Rank Six, he has yet to master his techniques and abilities and could have killed Zenitsu immediately in a year's time.[10] Physical Abilities Immense Speed & Reflexes: As a Thunder Breathing user turned Upper Rank demon, Kaigaku possesses tremendous movement speed and reflexes due to the Thunder Breathing swordsmanship style placing a heavy emphasis on swiftness and bursts of speed.[11] This combined with assimilating a large amount of Muzan's blood makes Kaigaku an extremely fast fighter, as shown when he could more than keep up with Zenitsu Agatsuma, a seasoned and skilled Demon Slayer that had trained under the same teacher to learn the same Breathing Style, and even overpower him for the majority of their clash."
    fullImg.src =smallImg.src;
  }
  function myFunctionuppermoon4(smallImg){
    fullImg = document.getElementById("imageBox");
    document.getElementById("uppermoondesciption").innerHTML="Gyutaro (妓夫ぎゅう太た郎ろう Gyūtarō?) was one of the primary antagonists in the Entertainment District Arc of Demon Slayer: Kimetsu no Yaiba. He was a demon affiliated with the Twelve Kizuki, holding the position of Upper Rank Six (上じょう弦げんの陸ろく Jōgen no Roku?), a position he shared with his younger sister, Daki.[3] Over a century ago, Gyutaro was a human who worked as a debt collector in the Rashomon Riverbank of Yoshiwara,[4][5] the lowest class in the Entertainment District, before he and Daki were turned into demons personally by Doma, who was Upper Rank Six at the time.[6]"
    fullImg.src =smallImg.src;
  }
  function myFunctionuppermoon5(smallImg){
    fullImg = document.getElementById("imageBox");
    document.getElementById("uppermoondesciption").innerHTML="Kokushibo (黒こく死し牟ぼう Kokushibō?) is a major supporting antagonist of Demon Slayer: Kimetsu no Yaiba. He is a demon affiliated with the Twelve Kizuki, holding the highest position, Upper Rank One (上じょう弦げんの壱いち Jōgen no Ichi?).[2] Nearly five centuries ago, during the Sengoku Era, Kokushibo was a human by the name of Michikatsu Tsugikuni (継つぎ国くに 巌みち勝かつ Tsugikuni Michikatsu?),[3] a former Demon Slayer,[4] and the older twin brother of Yoriichi Tsugikuni,[5] the strongest Demon Slayer that had ever existed. Kokushibo is also the ancestor of Muichiro Tokito and Yuichiro Tokito[6] and the one responsible for turning Zenitsu Agatsuma's senior, Kaigaku, into a demon and joining the Twelve Kizuki.[7] Kokushibo is a tall man of muscular build and pale skin complexion. He possesses long, spiky black hair with red tips that he keeps in a ponytail. His most notable feature is the three sets of eyes on his face with yellow irises and red flesh sclera that have black straight lines diverging from each iris. His middle set of eyes has the kanji of Upper Rank (上じょう弦げん Jōgen?) and daiji for One (壱いち Ichi?) engraved in them while his other sets of eyes feature black pupils and a cracked pattern in the irises. His top set of eyes replace his eyebrows. Kokushibo also has red markings resembling flames on the top left side of his forehead and the bottom right of his chin. His appearance is described to be profoundly majestic and dignified by Muichiro Tokito.[8]"
    fullImg.src =smallImg.src;
  }
  function myFunctionuppermoon6(smallImg){
    fullImg = document.getElementById("imageBox");
    document.getElementById("uppermoondesciption").innerHTML="Nakime (鳴なき女め Nakime?) is a recurring character and a supporting antagonist in the Infinity Castle Arc of Demon Slayer: Kimetsu no Yaiba. She is a demon who owns and controls the Infinity Castle and serves directly under Muzan Kibutsuji. Some time after Hantengu's death during the battle in the Swordsmith Village, Nakime attains the position of Upper Rank Four (上じょう弦げんの肆し Jōgen no Shi?) in the Twelve Kizuki.[1] Despite not displaying much in terms of fighting ability, as the holder of the fourth highest position in the Twelve Kizuki, Nakime is nonetheless an extremely powerful demon. She was capable of using her unorthodox Blood Demon Art to thwart the efforts of Obanai and Mitsuri at beheading her and stall the two Hashira for most of their battle, with neither of the two skilled combatants being able to so much as scratch her."
    fullImg.src =smallImg.src;
  }
  function myFunctionuppermoon7(smallImg){
    fullImg = document.getElementById("imageBox");
    document.getElementById("uppermoondesciption").innerHTML="Daki (堕だ姫き Daki?) was one of the primary antagonists in the Entertainment District Arc of Demon Slayer: Kimetsu no Yaiba. She was a demon affiliated with the Twelve Kizuki, being the secondary holder of the position of Upper Rank Six (上じょう弦げんの陸ろく Jōgen no Roku?),[5] a position she shared with the primary holder, her older brother, Gyutaro.[6] Over a century ago, Daki was a human child by the name of Ume (梅うめ Ume?), who lived in the Rashomon Riverbank of Yoshiwara, the lowest class of the Entertainment District,[7] before she and Gyutaro were turned into demons personally by Doma, who was Upper Rank Six at the time.[8] As the secondary holder of Upper Rank Six, Daki was an extremely powerful demon, having killed and devoured seven Hashira in the past. Her flesh detachment in the form of an sentient obi sash was strong enough to hold off the combined efforts of Zenitsu Agatsuma, Inosuke Hashibira, Makio, and Suma, the former two being seasoned Demon Slayers while the latter two being experienced kunoichi. Even while weakened due to dispersing her power through her obi across the city, she already proved a handful for Tanjiro Kamado, who had begun to actively use the Hinokami Kagura in combat. After her sentient flesh obi spread across the entire city had returned to her, Daki regained her full strength.[21] In this form, her speed was incomparable from before and her sashes also become more durable, allowing them to slice Nezuko Kamado's body in half and destroy an entire street's worth of buildings with ease.[22] Furthermore, once Gyutaro's eye was implanted in her, Daki's power was amplified once again, giving her improved speed and reflexes that enabled her to outclass the likes of Zenitsu's Thunderclap and Flash technique.[23] This also allowed Daki to coordinate her attacks with her brother, drastically increasing their offensive output and easily turning the tables against the combined efforts of Tanjiro, Zenitsu, Inosuke, and even Tengen Uzui, the Sound Hashira."
    fullImg.src =smallImg.src;
  }
  function myFunctionuppermoon8(smallImg){
    fullImg = document.getElementById("imageBox");
    document.getElementById("uppermoondesciption").innerHTML="Hantengu (半はん天てん狗ぐ Hantengu?), along with Gyokko, was one of the primary antagonists in the Swordsmith Village Arc of Demon Slayer: Kimetsu no Yaiba. He was a demon affiliated with the Twelve Kizuki, holding the position of Upper Rank Four (上じょう弦げんの肆し Jōgen no Shi?).[2] As the holder of the fourth highest title in the Twelve Kizuki, Hantengu was an extremely powerful demon. Through his Blood Demon Art, he is able to create four clones that were manifestations of his emotions, each of them possessing an Upper Rank demon's level of strength and having their own unique power, allowing him to outnumber and overwhelm the Demon Slayers that tried to slay him and giving him a wide arsenal. Most notoriously about Hantengu's unique power is that he takes advantage of the traditional method of decapitation to kill a demon, as beheading Hantengu's primary form will cause Sekido and Karaku to emerge and engage the threat. Beheading the first two manifestations further will then result in the release of Aizetsu and Urogi, and any subsequent decapitations of the clones will prove futile if Hantengu remains alive, or in Urogi's case, severed body parts can even use his Blood Demon Art to attack an opponent."
    fullImg.src =smallImg.src;
  }
  function myFunctionuppermoon9(smallImg){
    fullImg = document.getElementById("imageBox");
    document.getElementById("uppermoondesciption").innerHTML="Gyokko (玉ぎょ壺っこ Gyokko?), along with Hantengu, was one of the primary antagonists in the Swordsmith Village Arc of Demon Slayer: Kimetsu no Yaiba. He was a demon affiliated with the Twelve Kizuki, holding the position of Upper Rank Five (上じょう弦げんの伍ご Jōgen no Go?).[2] Before becoming a demon, he was a human by the name of Managi (益ま魚な儀ぎ Managi?).[1] As the holder of the fifth highest position in the Twelve Kizuki, Gyokko was an extremely powerful demon. His unique Blood Demon Art and techniques allow him to easily outclass the average demons and give him the necessary edge to overwhelm and kill even the Hashira, the most skilled and powerful swordsman in the Demon Slayer Corps. As Upper Rank Five, Gyokko is more powerful than Gyutaro and Daki, the former having killed 15 Hashira and the latter having killed 7.[4] Gyokko has displayed many impressive feats, such as spawning a plethora of powerful demon-like creatures with unique attacks, highly unorthodox movement both within and out of his pots, and a second hidden form. Most notably, in his duel with Muichiro Tokito, Gyokko was able to overpower and hold the Hashira back for the majority of their fight, even managing to bring him to the brink of death. If not for Gyokko's inherent egotistical nature and Muichiro awakening his Demon Slayer Mark, the Upper Rank would have more than likely been able to kill him."
    fullImg.src =smallImg.src;
  }
  function myFunctionlowerrank1(smallImg){
    fullImg = document.getElementById("imageBox");
    document.getElementById("lowerrankdescription").innerHTML="Enmu (魘えん夢む Enmu?) was the primary antagonist in the Mugen Train Arc of Demon Slayer: Kimetsu no Yaiba. He was a demon affiliated with the Twelve Kizuki, holding the position of Lower Rank One (下か弦げんの壱いち Kagen no Ichi?).[3] As Lower Rank One, Enmu was the strongest Lower Rank and closest to matching the strength of the Upper Ranks. Upon receiving more blood from Muzan Kibutsuji, his abilities were further enhanced. This level of ability was shown when Enmu's shapeshifting ability evolved to the point he was able fuse with a vehicle as big as a train. Additionally, his unorthodox sleep-based Blood Demon Art enabled him to render over 200 passengers in the Mugen Train, including the likes of the Hashira Kyojuro Rengoku, asleep and almost completely vulnerable. In direct combat, Enmu was able to hold his own against Tanjiro Kamado who had mastered Total Concentration Constant, evading his sword swings with ease and constantly putting the Demon Slayer to sleep with his spells.[10] In his fused form, every single inch of the Mugen Train became his body, which took the combined effort of Tanjiro, Zenitsu, Inosuke, Nezuko and Kyojuro himself to ward off and defeat. Despite all this, Enmu realized after his defeat that he wasn't quite at the level of an Upper Rank demon and he still paled in comparison to the likes of Daki and Gyutaro, the lowest members of the Upper Ranks.[11] Enhanced Speed & Reflexes: As a member of the Twelve Kizuki, Enmu had assimilated a high concentration of Muzan's blood which has greatly improved his physical abilities and attributes, most notably his movement speed and reflexes. This was shown during his initial battle against Tanjiro where he was able to dodge and react to every single one of the Demon Slayer's attacks with little effort, even moving so fast that Tanjiro had trouble keeping up."
    fullImg.src =smallImg.src;
  }
  function myFunctionlowerrank2(smallImg){
    fullImg = document.getElementById("imageBox");
    document.getElementById("lowerrankdescription").innerHTML="Kamanue (釜かま鵺ぬえ Kamanue?) was a member of the Twelve Kizuki, having held the new position of Lower Rank Six (下か弦げんの陸ろく Kagen no Roku?).[1] Little was known about Kamanue's strength and abilities as a demon, but it can be assumed that he was much stronger than the average demon and likely surpassed Kyogai, the former member of the Twelve Kizuki whose place he took. Kamanue was a very anxious and restive individual. He constantly wore a scared expression due to the fact that he felt weak and vulnerable as the lowest of the Lower Ranks. He appeared to be constantly skittish during his short time at the Infinity Castle. As with most demons, his loyalty to Muzan Kibutsuji, though steadfast, was built on great fear, sweating profusely when he heard the Demon King's voice and being unable to say a word when he was challenged to continue speaking his mind when Muzan questioned his loyalty."
    fullImg.src =smallImg.src;
  }
  function myFunctionlowerrank3(smallImg){
    fullImg = document.getElementById("imageBox");
    document.getElementById("lowerrankdescription").innerHTML="Kyogai (響きょう凱がい Kyōgai?), also known as the Drum Demon (鼓つづみ鬼おに Tsuzumi Oni?) was the primary antagonist in the Tsuzumi Mansion Arc of Demon Slayer: Kimetsu no Yaiba. He was a demon formerly affiliated with the Twelve Kizuki, having previously held the position of Lower Rank Six (下か弦げんの陸ろく Kagen no Roku?) before Muzan Kibutsuji excommunicated him for reaching his limit as a demon and losing his ability to become stronger.[1] Kyogai was a relatively powerful demon and was the strongest one Tanjiro had faced at that point. His unusual Blood Demon Art and obsessive hunger for Kiyoshi's blood made him all the more dangerous. He held off a Mizunoto-ranked Tanjiro and Inosuke together with ease and his slashes prevented them from getting a good strike. His constant changing of the room's orientation also served him well, as Tanjiro became greatly disoriented and was barely survive getting hit. However, the range and potency of his attacks ultimately was not enough to overcome Tanjiro's will to keep fighting, as the Demon Slayer was able to adapt to his techniques in a relatively short span of time."
    fullImg.src =smallImg.src;
  }
  function myFunctionlowerrank4(smallImg){
    fullImg = document.getElementById("imageBox");
    document.getElementById("lowerrankdescription").innerHTML="Mukago (零む余か子ご Mukago?) was a member of the Twelve Kizuki, having held the position of Lower Rank Four (下か弦げんの肆し Kagen no Shi?).[1] Little was known about Mukago's strength and abilities as a demon, but it can be assumed that she was stronger than an average demon and superior in power to Kamanue, as she was given a higher Lower Rank position than him. Like most demons, Mukago held great fear and respect for Muzan Kibutsuji. However, out of all the Lower Ranks, she was also shown to be the most cowardly. As stated by Muzan through reading her thoughts, Mukago had no intention of battling the Demon Slayer Corps' Hashira and planned to flee at the mere mention of one, noted to have done so numerous times. When Muzan learned of this, Mukago attempted to deny her thoughts in an attempt to appease him."
    fullImg.src =smallImg.src;
  } 
  function myFunctionlowerrank5(smallImg){
    fullImg = document.getElementById("imageBox");
    document.getElementById("lowerrankdescription").innerHTML="Rokuro (轆ろく轤ろ Rokuro?) was a member of the Twelve Kizuki, having held the position of Lower Rank Two (下か弦げんの弐に Kagen no Ni?).[1] As Lower Rank Two, Rokuro was the second strongest demon among the Lower Ranks, though his true strength is unknown. He would have evidently been a very strong demon as the only demon ranked above him was the very powerful Enmu, and he claims that he can acclimate a portion of Muzan's blood without fail, which has been shown to induce torturous pain even in low amounts. Muzan's statement that the extremely formidable Rui can match Lower Rank Two and One in strength could be a potential hint to Rokuro's power. As with most demons, Rokuro greatly respected and feared Muzan Kibutsuji as his leader. After almost every Lower Ranks had been killed by the Demon King, Rokuro was visibly scared that the same would happen to him and resorted to begging his leader for more blood to increase his strength so he wouldn’t die, showing quite a somewhat cowardly demeanor. However, in spite of this, Rokuro appeared to be very confident in the potential of his abilities as a demon, since he claimed that if he received just a little more of Muzan's blood he could definitely become a strong fighter worthy of being in the ranks of the Twelve Kizuki, which showed he had a great resolve and passion for his role."
    fullImg.src =smallImg.src;
  } 
  function myFunctionlowerrank6(smallImg){
    fullImg = document.getElementById("imageBox");
    document.getElementById("lowerrankdescription").innerHTML="Rui (累るい Rui?) was the primary antagonist in the Mount Natagumo Arc of Demon Slayer: Kimetsu no Yaiba. He was a demon affiliated with the Twelve Kizuki, holding the position of Lower Rank Five (下か弦げんの伍ご Kagen no Go?).[3] As Lower Rank Five of the Twelve Kizuki, Rui was a very powerful demon. His strength and power easily surpassed that of most other demons, since he was easily able to conquer and cohere numerous demons of Mount Natagumo and force them to work for him and become members of his family. Evidence of his strength was further shown when he was able to easily overwhelm a talented fighter like Tanjiro Kamado. Furthermore, demons empowered through his blood were strong enough to kill scores of Demon Slayers easily. However, Rui's power still paled in comparison to the Hashira, having his technique easily overcome and later was effortlessly decapitated by Giyu Tomioka.[5] Although Rui was only a demon for 20 years, he was stated to be highly capable and was well-liked by Muzan himself. It was also stated that Rui was as skillful as Lower Rank Two or One but was not obsessed with numbers and did not feel the need to enter a Blood Battle with them in order to replace them. Muzan even went as far as to expect Rui to be able to defeat a Hashira by himself despite him being a Lower Rank. It was also stated that if Rui recovered all of the power he shared with his family, he could have been a good match for the Hashira, and possibly could have been stronger than them.[2]"
    fullImg.src =smallImg.src;
  } 
  function myFunctionlowerrank7(smallImg){
    fullImg = document.getElementById("imageBox");
    document.getElementById("lowerrankdescription").innerHTML="Wakuraba (病わくら葉ば Wakuraba?) was a member of the Twelve Kizuki, having held the position of Lower Rank Three (下か弦げんの参さん Kagen no San?).[1] As Lower Three of the Twelve Kizuki, Wakuraba was undoubtedly a very powerful demon. He claimed that he was able to rise up in rank, indicating that he initially was Lower Six and was strong enough to move up. However, his true strength remains unknown due to the Demon King's act of killing him, and it was apparent that he paled in comparison to the likes of Rui and Enmu. He at least showed enough confidence in himself when he plotted to try and escape his master in an unfamiliar location. Wakuraba was a man of average stature who had pale, grayish-white skin, with what appeared to be three large, cross-shaped scars cut into his cheeks and the center of his forehead and noticeably elf-like, pointed ears. His eyes were wide and sharp with orange irises, with the kanjis for Lower Three etched into his left eye, as well as short, black hair and a widow's peak. Wakuraba wore a dotted, bamboo-colored yukata with a pinstripe pattern, a piece of dark cloth around his waist, and a lighter one around his neck, as well as two golden hoop earrings on each ear and a pair of wooden sandals with black straps."
    fullImg.src =smallImg.src;
  } 
  
  
/*
function myFunction2(){
  document.getElementById("demo").innerHTML=" Tanjiro Kamado's goal are to avenge his family and his idol Kyojiro Rengoku by Killing Muzan Kibutsuji and Akaza, prevent other from suffering the same tragedy as he and his sister, turn Nezuko back into a human, and proteck nezuko and his friends from evil demons and other dangerous in the world. ";
} 
*/
